version: '3'

services:
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        - github_username=${USERNAME}
        - github_token=${TOKEN}
    restart: always
    ports:
      - "80:80"

  read:
    depends_on:
      - db
    container_name: read
    build:
      context: ./read
      dockerfile: Dockerfile
      args:
        - github_username=${USERNAME}
        - github_token=${TOKEN}
    restart: always
    ports:
      - "8081:8081"

  write:
    depends_on:
      - db
    container_name: write
    build:
      context: ./write
      dockerfile: Dockerfile
      args:
        - github_username=${USERNAME}
        - github_token=${TOKEN}
    restart: always
    ports:
      - "8082:8082"

  gateway:
    depends_on:
      - read
      - write
    container_name: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        - github_username=${USERNAME}
        - github_token=${TOKEN}
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - $PWD/gateway:/settings
    environment:
      - CONFIG_FILE=/settings/config.json
      - PORT=:8080

