apiVersion: apps/v1
kind: Deployment
metadata:
  name: read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: read
  template:
    metadata:
      labels:
        app: read
    spec:
      containers:
      - name: read
        image: ghcr.io/ebagos/trial/read:latest
        env:
        - name: DB_URL
          value: "http://DB-SVC:8083/read"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: read-svc
spec:
  selector:
    app: read
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
