apiVersion: apps/v1
kind: Deployment
metadata:
  name: write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: write
  template:
    metadata:
      labels:
        app: write
    spec:
      containers:
      - name: write
        image: ghcr.io/ebagos/trial/write:latest
        env:
        - name: DB_URL
          value: "http://db-svc:8083/write"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: write-svc
spec:
  selector:
    app: write
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
