apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: ghcr.io/ebagos/trial/gateway
        env:
        - name: PORT
          value: ":8080"
#        - name: CONFIG_FILE
#          value: "/setting/config.json"
#        volumeMounts:
#        - name: config
#          mountPath: "/setting"
#          readOnly: true
        ports:
        - containerPort: 8080
#      volumes:
#      - name: config
#        configMap:
#          name: config-jsons
#          items:
#          - key: config
#            path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
